name = "HelloWorld"
uuid = "e7189086-d955-406d-ac96-9d15fb90a353"
authors = ["bcoggins <bcoggins@nd.edu>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
